packages:
  - 'apps/*'
  - 'libs/*'
  - 'packages/*'
  - 'libs/frontend/shared/*'
  - 'libs/frontend/features/*'
  - 'libs/frontend/shells/*'
  - 'libs/frontend/*'
onlyBuiltDependencies:
  - '@parcel/watcher'
