import type { Database } from 'better-sqlite3';
import { customAlphabet } from 'nanoid';
import { ProblemError } from '../errors/problem-error';
import type { MessageStreamEvent } from '../plugins/message-stream';
import type { MessagePayload } from '../schemas/message';
import { getConversationById } from './conversation-service';

const messageIdGenerator = customAlphabet(
  '0123456789abcdefghijklmnopqrstuvwxyz',
  12,
);

interface ListMessagesQuery {
  page: number;
  pageSize: number;
}

interface MessageRow {
  content: string;
  conversation_id: string;
  created_at: string;
  error_message: string | null;
  id: string;
  retry_count: number;
  role: MessagePayload['role'];
  status: MessagePayload['status'];
  updated_at: string;
}

interface MessageStreamBroker {
  publish(event: MessageStreamEvent): void;
}

function mapMessageRow(row: MessageRow): MessagePayload {
  return {
    id: row.id,
    conversationId: row.conversation_id,
    role: row.role,
    content: row.content,
    status: row.status,
    errorMessage: row.error_message,
    retryCount: row.retry_count,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function createMessageId() {
  return `msg_${messageIdGenerator()}`;
}

function throwMessageNotFound(messageId: string): never {
  throw new ProblemError({
    type: 'https://team-ai.dev/problems/message-not-found',
    title: 'Message Not Found',
    status: 404,
    detail: `Message ${messageId} was not found`,
  });
}

function buildAssistantResponse(prompt: string): string {
  if (prompt.toLowerCase().includes('[fail]')) {
    throw new Error('Synthetic local assistant failure');
  }

  return [
    'Local assistant response ready.',
    `I received: ${prompt}`,
    'This reply is generated by the desktop local server stream.',
  ].join(' ');
}

function splitIntoChunks(content: string): string[] {
  return content.match(/.{1,24}/g) ?? [content];
}

function createMessage(
  conversationId: string,
  role: MessagePayload['role'],
  content: string,
  status: MessagePayload['status'],
): MessagePayload {
  const now = new Date().toISOString();

  return {
    id: createMessageId(),
    conversationId,
    role,
    content,
    status,
    errorMessage: null,
    retryCount: 0,
    createdAt: now,
    updatedAt: now,
  };
}

function persistMessage(sqlite: Database, message: MessagePayload) {
  sqlite
    .prepare(
      `
        INSERT INTO messages (
          id,
          conversation_id,
          role,
          content,
          status,
          error_message,
          retry_count,
          created_at,
          updated_at,
          deleted_at
        )
        VALUES (
          @id,
          @conversationId,
          @role,
          @content,
          @status,
          @errorMessage,
          @retryCount,
          @createdAt,
          @updatedAt,
          NULL
        )
      `,
    )
    .run(message);
}

export async function listMessagesByConversation(
  sqlite: Database,
  conversationId: string,
  query: ListMessagesQuery,
) {
  await getConversationById(sqlite, conversationId);

  const { page, pageSize } = query;
  const offset = (page - 1) * pageSize;
  const items = sqlite
    .prepare(
      `
        SELECT
          id,
          conversation_id,
          role,
          content,
          status,
          error_message,
          retry_count,
          created_at,
          updated_at
        FROM messages
        WHERE conversation_id = @conversationId AND deleted_at IS NULL
        ORDER BY created_at ASC
        LIMIT @limit OFFSET @offset
      `,
    )
    .all({
      conversationId,
      limit: pageSize,
      offset,
    }) as MessageRow[];

  const total = sqlite
    .prepare(
      `
        SELECT COUNT(*) AS count
        FROM messages
        WHERE conversation_id = @conversationId AND deleted_at IS NULL
      `,
    )
    .get({ conversationId }) as { count: number };

  return {
    conversationId,
    items: items.map(mapMessageRow),
    page,
    pageSize,
    total: total.count,
  };
}

export async function createMessagePair(
  sqlite: Database,
  conversationId: string,
  content: string,
) {
  await getConversationById(sqlite, conversationId);

  const userMessage = createMessage(conversationId, 'user', content, 'completed');
  const assistantMessage = createMessage(conversationId, 'assistant', '', 'pending');

  const transaction = sqlite.transaction(() => {
    persistMessage(sqlite, userMessage);
    persistMessage(sqlite, assistantMessage);
  });

  transaction();

  return {
    userMessage,
    assistantMessage,
  };
}

export async function getMessageById(
  sqlite: Database,
  messageId: string,
): Promise<MessagePayload> {
  const row = sqlite
    .prepare(
      `
        SELECT
          id,
          conversation_id,
          role,
          content,
          status,
          error_message,
          retry_count,
          created_at,
          updated_at
        FROM messages
        WHERE id = ? AND deleted_at IS NULL
      `,
    )
    .get(messageId) as MessageRow | undefined;

  if (!row) {
    throwMessageNotFound(messageId);
  }

  return mapMessageRow(row);
}

function getPromptForAssistantMessage(
  sqlite: Database,
  assistantMessage: MessagePayload,
): string {
  const row = sqlite
    .prepare(
      `
        SELECT content
        FROM messages
        WHERE
          conversation_id = @conversationId
          AND role = 'user'
          AND deleted_at IS NULL
          AND created_at <= @createdAt
        ORDER BY created_at DESC
        LIMIT 1
      `,
    )
    .get({
      conversationId: assistantMessage.conversationId,
      createdAt: assistantMessage.createdAt,
    }) as { content: string } | undefined;

  if (!row) {
    throw new Error(`Unable to locate prompt for message ${assistantMessage.id}`);
  }

  return row.content;
}

function updateMessageRuntime(
  sqlite: Database,
  message: MessagePayload,
): MessagePayload {
  sqlite
    .prepare(
      `
        UPDATE messages
        SET
          content = @content,
          status = @status,
          error_message = @errorMessage,
          retry_count = @retryCount,
          updated_at = @updatedAt
        WHERE id = @id
      `,
    )
    .run(message);

  return message;
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function streamAssistantReply(
  sqlite: Database,
  broker: MessageStreamBroker,
  assistantMessageId: string,
): Promise<void> {
  const assistantMessage = await getMessageById(sqlite, assistantMessageId);

  if (assistantMessage.role !== 'assistant') {
    throw new ProblemError({
      type: 'https://team-ai.dev/problems/retry-not-supported',
      title: 'Retry Not Supported',
      status: 409,
      detail: 'Only assistant messages can be retried',
    });
  }

  const prompt = getPromptForAssistantMessage(sqlite, assistantMessage);
  let current: MessagePayload = {
    ...assistantMessage,
    content: '',
    errorMessage: null,
    status: 'streaming',
    updatedAt: new Date().toISOString(),
  };

  updateMessageRuntime(sqlite, current);

  try {
    const response = buildAssistantResponse(prompt);
    const chunks = splitIntoChunks(response);

    for (const chunk of chunks) {
      await sleep(40);
      current = {
        ...current,
        content: `${current.content}${chunk}`,
        updatedAt: new Date().toISOString(),
      };
      updateMessageRuntime(sqlite, current);
      broker.publish({
        type: 'message.chunk',
        at: current.updatedAt,
        conversationId: current.conversationId,
        messageId: current.id,
        role: 'assistant',
        content: chunk,
        status: current.status,
      });
    }

    current = {
      ...current,
      status: 'completed',
      updatedAt: new Date().toISOString(),
    };
    updateMessageRuntime(sqlite, current);
    broker.publish({
      type: 'message.completed',
      at: current.updatedAt,
      conversationId: current.conversationId,
      messageId: current.id,
      role: 'assistant',
      content: current.content,
      status: current.status,
    });
  } catch (error) {
    current = {
      ...current,
      status: 'failed',
      errorMessage:
        error instanceof Error ? error.message : 'Unknown assistant generation error',
      updatedAt: new Date().toISOString(),
    };
    updateMessageRuntime(sqlite, current);
    broker.publish({
      type: 'message.failed',
      at: current.updatedAt,
      conversationId: current.conversationId,
      messageId: current.id,
      role: 'assistant',
      errorMessage: current.errorMessage,
      status: current.status,
    });
  }
}

export async function retryMessage(
  sqlite: Database,
  messageId: string,
): Promise<MessagePayload> {
  const message = await getMessageById(sqlite, messageId);

  if (message.role !== 'assistant' || message.status !== 'failed') {
    throw new ProblemError({
      type: 'https://team-ai.dev/problems/retry-not-supported',
      title: 'Retry Not Supported',
      status: 409,
      detail: 'Only failed assistant messages can be retried',
    });
  }

  const next: MessagePayload = {
    ...message,
    content: '',
    errorMessage: null,
    retryCount: message.retryCount + 1,
    status: 'pending',
    updatedAt: new Date().toISOString(),
  };

  return updateMessageRuntime(sqlite, next);
}
