spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:teamai_dev}
    username: ${DB_USERNAME:teamai_dev}
    password: ${DB_PASSWORD:teamai_dev}
  flyway:
    clean-disabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG
    reengineering.ddd: DEBUG
