#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Ensure nvm is available and node is in PATH
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

nx affected -t spotlessApply
nx affected -t typecheck
nx affected -t format:write
nx affected -t lint --fix
